config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "users#index"

  # get '/home' => 'users#content', as: :user_content

  root "home#index"
  get '/home/link_content', to: 'home#link_content', as: :home_link_content
  get '/home/form_content', to: 'home#form_content', as: :view_home_form_content
  post '/home/form_content', to: 'home#form_content', as: :home_form_content
  get '/home/src_content', to: 'home#src_content', as: :home_src_content
  post '/home/stream_content', to: 'home#stream_content', as: :home_stream_content
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def link_content
  end

  def form_content
    if params[:redirect] == "true"
      redirect_to view_home_form_content_path
    end
  end

  def src_content

  end

  def stream_content
    respond_to do |format|
      if params[:redirect] == "true"
        format.turbo_stream {
          render turbo_stream: turbo_stream.action(:redirect, home_link_content_path)
        }
      else
        format.turbo_stream
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/form_content.html.erb
<%= turbo_frame_tag "form_frame" do %>
  form data response
<% end %>

app/views/home/index.html.erb
<h1>Turbo Frames</h1>

Current Time: <%= Time.current %> (for seeing page reloads)

<h2>A link that loads in a Turbo Frame</h2>
<%= turbo_frame_tag "link_frame" do %>
  <%= link_to "Load content in frame", home_link_content_path %>
  <br>
  <%= link_to "Bypass frame and do a full page navigation", home_link_content_path, data:  { turbo_frame: '_top' } %>
<% end %>
<br>
<%= link_to "Load content in frame from outside the tag", home_link_content_path, data: { turbo_frame: 'link_frame' } %>

<br>
<h2>A form that submits in a Turbo Frame</h2>
<%= turbo_frame_tag "form_frame" do %>
  <%= form_with url: home_form_content_path, method: :post do |form| %>
    <%= form.label :name, "Enter your name:" %>
    <%= form.text_field :name %>
    <%= form.submit "Submit" %>
  <% end %>

  <%= form_with url: home_form_content_path, method: :post, data: { turbo_frame: "_top" } do |form| %>
    <%= form.label :name, "Enter your name:" %>
    <%= form.text_field :name %>
    <%= form.hidden_field :redirect, value: "true" %>
    <%= form.submit "Form that breaks out of the current turbo frame" %>
  <% end %>
<% end %>

<%= form_with url: home_form_content_path, method: :post, data: {turbo_frame: 'form_frame'} do |form| %>
  <%= form.label :name, "Enter your name:" %>
  <%= form.text_field :name %>
  <%= form.submit "Submit form that's outside of the frame tag" %>
<% end %>

<h2>Changing the src of a Turbo Frame</h2>
<%= turbo_frame_tag "src_frame" do %>
  Initial content of the frame.
<% end %>
<script>
  setTimeout(function() {
    document.getElementById("src_frame").setAttribute("src", "<%= home_src_content_path %>");
  }, 5000)
</script>

<h2>Eager loading data into a Turbo Frame</h2>
<%= turbo_frame_tag "src_frame", src: home_src_content_path do %>
  Initial content of the frame.
<% end %>

<hr>

<h1>Turbo Streams</h1>
<div id="dynamic_content">
  <p>Current time: <%= Time.current %></p>
</div>
<div id="dynamic_content2">
  <p>Current time: <%= Time.current %></p>
</div>

<%= form_with url: home_stream_content_path, method: :post do |form| %>
  <%= form.label :name, "Enter your name:" %>
  <%= form.text_field :name %>
  <%= form.submit "Submit" %>
<% end %>


<%= form_with url: home_stream_content_path, method: :post do |form| %>
  <%= form.label :name, "Enter your name:" %>
  <%= form.hidden_field :redirect, value: "true" %>
  <%= form.text_field :name %>
  <%= form.submit "Submit & Breakout" %>
<% end %>

app/views/home/link_content.html.erb
<%= turbo_frame_tag "link_frame" do %>
  this is content loaded in a turbo frame
<% end %>

app/views/home/src_content.html.erb
<%= turbo_frame_tag "src_frame" do %>
  <p>Current time: <%= Time.current %></p>

  This is great for adding dynamic content. Just change the src from javascript and theres no need to make fetch requests.
<% end %>

app/views/home/stream_content.turbo_stream.erb
<%= turbo_stream.replace 'dynamic_content' do %>
  This was updated from a turbo stream replace action
<% end %>

<%= turbo_stream.append 'dynamic_content2' do %>
  <p>This is an appended paragraph to the dynamic content.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Testing Turbo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>